### ISSUE TITLE
CUDA out of memory after some iters when training

### ISSUE THREAD

**Issue by starsky0426** [luca-medeiros/lightning-sam#4]
It's the best SAM fine tune code i've found, thank you so much!

I have a single gpu with 12GB memory, the memory kept growing when training, and ran out of memory after some time. Is it related to lightning?

**Comment by luca-medeiros** [comment]
Hey, @starsky0426 appreciate the feedback!

That's weird... but with 12GB how did you set your batch size?
I'm thinking it might be related to how I'm averaging the losses in AverageMeter.
https://github.com/luca-medeiros/lightning-sam/blob/94fbe0d36f856ada8fcf42a7ca0c9a65a504ab8e/src/train.py#L108-L111
Mind trying sending the losses to CPU to see if it fixes the issue? `loss.item().cpu()`
Or even removing those lines together with the print.
If that's not the case, I would guess that some of your images have way more instances than others. Does the VRAM increase linearly?

**Comment by starsky0426** [comment]
> Hey, @starsky0426 appreciate the feedback!
> 
> That's weird... but with 12GB how did you set your batch size? I'm thinking it might be related to how I'm averaging the losses in AverageMeter.
> 
> https://github.com/luca-medeiros/lightning-sam/blob/94fbe0d36f856ada8fcf42a7ca0c9a65a504ab8e/src/train.py#L108-L111
> 
> 
> Mind trying sending the losses to CPU to see if it fixes the issue? `loss.item().cpu()`
> Or even removing those lines together with the print.
> If that's not the case, I would guess that some of your images have way more instances than others. Does the VRAM increase linearly?

Thank you for your reply!

My specification is:

RTX4070Ti 12GB, cuda 11.7, nvidia-driver-530, ubuntu 20.04
config:{
    "num_devices": 1,
    "batch_size": 2,
    "num_workers": 4,
}

I tried to remove lightning code and use pure pytorch implementation to train, the memory issue seems to be fixed, but the training speed is quite slow🤔.

**Comment by luca-medeiros** [comment]
To be honest, I've only tried on A100s and haven't faced a similar issue.
I'll try contacting some people from Lightning to see if they have a clue about it.
Thanks for trying it out!

**Comment by luca-medeiros** [comment]
@awaelchli Appreciate the time you took to check this out!
Yea, I can't think of any line where I'm accumulating stuff that would cause this.

**Comment by starsky0426** [comment]
> 

Hi, @awaelchli

I made a dummy dataset using the following code:

```python
class DummyCOCODataset(Dataset):

    def __init__(self, root_dir, annotation_file, transform=None):
        pass

    def __len__(self):
        return 5000

    def __getitem__(self, index):
        # Create dummy image tensor
        image = torch.randn((3, 1024, 1024))

        return image, torch.ones([4, 4]), torch.ones([4, 1024, 1024]).float()
```
With training in serveral minutes with batch_size=4, the VRAM usage is below 7GB.
But when i switched back to COCO dataset, the VRAM usage with batch_size=1 is nearly 11GB, and after about 10 minutes it grows up to 12GB and ran out of memory in my GPU 🙃

I removed the lightning related code, and train with pure pytorch, and the memory cost is nearly the same, the experiment yesterday was using cpu to train by mistake, I'm sorry 😅.

**Comment by harindra2002** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 GiB (GPU 0; 39.56 GiB total capacity; 29.88 GiB already allocated; 8.66 GiB free; 30.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Why is PyTorch allocating 30.39GB

**Comment by harindra2002** [comment]
I am using A100 GPU

**Comment by harindra2002** [comment]
When I try to run with a batch size of 4 it runs for 525 Iterations on the first epoch and runs out of RAM
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 872.00 MiB (GPU 0; 39.56 GiB total capacity; 33.94 GiB already allocated; 678.56 MiB free; 38.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by harindra2002** [comment]
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 GiB (GPU 0; 39.56 GiB total capacity; 29.88 GiB already allocated; 8.66 GiB free; 30.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF Why is PyTorch allocating 30.39GB

This is with a batch size of 12

**Comment by harindra2002** [comment]
I removed lightning and used pure PyTorch but even that does not seem to work

**Comment by harindra2002** [comment]
@luca-medeiros Can you please help me with this

**Comment by luca-medeiros** [comment]
@harindra2002 
Don't think I can help without knowing the dataset you are using. The usage of vram depends on several factors.
Any extra information or profiling/debugging?

**Comment by harindra2002** [comment]
I am using a satellite images custom dataset, about 3500 images, resolution: 512*512. 
Task: Segmenting farm boundaries
